// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Enquiry form', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Enquiry form', async function() {
    await driver.get("https://sciadev-scia.cs31.force.com/enquiryform")
    vars["href"] = await driver.executeScript("return window.location.href")
    await driver.findElement(By.css(".multiselect")).click()
    await driver.findElement(By.css(".ng-binding:nth-child(1) .checkbox")).click()
    await driver.findElement(By.id("Are you *")).click()
    {
      const dropdown = await driver.findElement(By.id("Are you *"))
      await dropdown.findElement(By.xpath("//option[. = 'Person with a disability']")).click()
    }
    await driver.findElement(By.id("First Name *")).click()
    await driver.findElement(By.id("First Name *")).sendKeys("Selenium")
    await driver.findElement(By.id("Last Name *")).click()
    await driver.findElement(By.id("Last Name *")).sendKeys("Test")
    await driver.findElement(By.id("Email *")).click()
    await driver.findElement(By.id("Email *")).sendKeys("ajdf@gmail.com")
    await driver.findElement(By.css(".row:nth-child(4) > .col-md-8:nth-child(2) .form-group")).click()
    await driver.findElement(By.id("memberPhone")).click()
    await driver.findElement(By.id("memberPhone")).sendKeys("1234567456")
    await driver.findElement(By.id("State *")).click()
    await driver.findElement(By.id("State *")).sendKeys("Arizona")
    await driver.findElement(By.id("How did you hear about us? *")).click()
    {
      const dropdown = await driver.findElement(By.id("How did you hear about us? *"))
      await dropdown.findElement(By.xpath("//option[. = 'Existing Client']")).click()
    }
    await driver.findElement(By.css(".donate-now")).click()
    await driver.sleep(12000)
    vars["new_href"] = await driver.executeScript("return window.location.href")
    if (!!await driver.executeScript("return (arguments[0] == arguments[1])", vars["href"],vars["new_href"])) {
      await driver.close()
    }
  })
})
