// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Anonymous', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Anonymous', async function() {
    await driver.get("https://sciadev-scia.cs31.force.com/feedbackform")
    vars["href"] = await driver.executeScript("return window.location.href")
    await driver.findElement(By.xpath("//div/input")).sendKeys("Selenium")
    await driver.findElement(By.xpath("//div[2]/form-group/div/div/div/input")).sendKeys("Test")
    await driver.findElement(By.name("isAnonymous")).click()
    {
      const dropdown = await driver.findElement(By.id("What is the nature of the feedback? *"))
      await dropdown.findElement(By.css("*[value='Compliment']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("What does the feedback relate to? *"))
      await dropdown.findElement(By.css("*[value='Accommodation']")).click()
    }
    await driver.findElement(By.xpath("//textarea")).click()
    await driver.findElement(By.xpath("//textarea")).sendKeys("Test")
    await driver.findElement(By.css(".donate-now")).click()
    await driver.sleep(12000)
    vars["new_href"] = await driver.executeScript("return window.location.href")
    if (!!await driver.executeScript("return (arguments[0] == arguments[1])", vars["href"],vars["new_href"])) {
      await driver.close()
    }
  })
})
